server:
    port: 8080

spring:
    application:
        name: Record-Catalog

    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password: password

    jpa:
        open-in-view: true
        defer-datasource-initialization: true

    h2:
        console:
            enabled: true