server:
    port: 8080

spring:
    application:
        name: Record-Catalog

    datasource:
        url: jdbc:postgresql://localhost:5432/recordcatalog
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: postgres