INSERT INTO Format VALUES (1, 'Vinyl');
INSERT INTO Format VALUES (2, 'Cassette');
INSERT INTO Format VALUES (3, 'CD');
INSERT INTO Format VALUES (4, 'Digital');

INSERT INTO Artist VALUES (1, 'Alice in Chains');
INSERT INTO Artist VALUES (2, 'Stone Temple Pilots');
INSERT INTO Artist VALUES (3, 'Soundgarden');
INSERT INTO Artist VALUES (4, 'Genesis');
INSERT INTO Artist VALUES (5, 'Blur');
INSERT INTO Artist VALUES (6, 'Gorillaz');
INSERT INTO Artist VALUES (7, 'Nirvana');
INSERT INTO Artist VALUES (8, 'Depeche Mode');
INSERT INTO Artist VALUES (9, 'Pink Floyd');
INSERT INTO Artist VALUES (10, 'David Bowie');
INSERT INTO Artist VALUES (11, 'Led Zeppelin');
INSERT INTO Artist VALUES (12, 'Emerson, Lake & Palmer');
INSERT INTO Artist VALUES (13, 'King Crimson');
INSERT INTO Artist VALUES (14, 'Phil Collins');
INSERT INTO Artist VALUES (15, 'Jean-Michel Jarre');
INSERT INTO Artist VALUES (16, 'Supertramp');
INSERT INTO Artist VALUES (17, 'Pearl Jam');
INSERT INTO Artist VALUES (18, 'Audioslave');
